anchors:
  ## This section exists to provide anchors for the pipelines below.
  ## Place config files used multiple times as additional anchors here to avoid duplication.
  - &tools-admin "../gomatic-secure/gocd/vars/tools/admin.yml"

  - &deployment-edx      "../gomatic-secure/gocd/vars/tools/deployments/edx.yml"
  - &deployment-edge     "../gomatic-secure/gocd/vars/tools/deployments/edge.yml"
  - &deployment-mckinsey "../gomatic-secure/gocd/vars/tools/deployments/mckinsey.yml"

  - &stage-edx     "../gomatic-secure/gocd/vars/tools/environment-deployments/stage-edx.yml"
  - &prod-edx      "../gomatic-secure/gocd/vars/tools/environment-deployments/prod-edx.yml"
  - &prod-edge     "../gomatic-secure/gocd/vars/tools/environment-deployments/prod-edge.yml"
  - &prod-mckinsey "../gomatic-secure/gocd/vars/tools/environment-deployments/prod-mckinsey.yml"
  - &loadtest-edx  "../gomatic-secure/gocd/vars/tools/environment-deployments/loadtest-edx.yml"

  - &play-edxapp      "../gomatic-secure/gocd/vars/tools/plays/edxapp.yml"
  - &play-ecommerce   "../gomatic-secure/gocd/vars/tools/plays/ecommerce.yml"
  - &play-ecomworker  "../gomatic-secure/gocd/vars/tools/plays/ecomworker.yml"
  - &play-credentials "../gomatic-secure/gocd/vars/tools/plays/credentials.yml"
  - &play-programs    "../gomatic-secure/gocd/vars/tools/plays/programs.yml"
  - &play-discovery   "../gomatic-secure/gocd/vars/tools/plays/discovery.yml"

  - &prod-stage-edxapp         "../gomatic-secure/gocd/vars/tools/environment-play/prod-stage-edxapp.yml"
  - &prod-stage-edxapp-private "../gomatic-secure/gocd/vars/tools/environment-play/prod-stage-edxapp-private.yml"

  - &prerelease_upstream     "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-edxapp-prerelease-upstream.yml"
  - &prod-edx-edxapp-latest  "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edx-edxapp-latest.yml"
  - &prod-edge-edxapp-latest "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edge-edxapp-latest.yml"

tools:
  ## Start of 'Janitors' pipeline group

  #ASG cleanup for edge
  - script: edxpipelines/pipelines/asg_cleanup.py
    input_files:
      - *tools-admin
      - *deployment-edge
      - "../gomatic-secure/gocd/vars/tools/asg-cleanup-edge.yml"
    enabled: True

  #ASG cleanup for edx
  - script: edxpipelines/pipelines/asg_cleanup.py
    input_files:
      - *tools-admin
      - *deployment-edx
      - "../gomatic-secure/gocd/vars/tools/asg-cleanup-edx.yml"
    enabled: True

  #ASG cleanup for mckinsey
  - script: edxpipelines/pipelines/asg_cleanup.py
    input_files:
      - *tools-admin
      - *deployment-mckinsey
      - "../gomatic-secure/gocd/vars/tools/asg-cleanup-mckinsey.yml"
    enabled: True
  # End of 'Janitors' pipeline group

  - script: edxpipelines/pipelines/build_edxapp_ami.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/build-edxapp-ami.yml"
    enabled: False

  ## Start of 'deploy' pipeline group
  - script: edxpipelines/pipelines/deploy_ami.py
    input_files:
      - *tools-admin
      - *deployment-edx
      - "../gomatic-secure/gocd/vars/tools/deploy_edx_ami.yml"
    enabled: True

  - script: edxpipelines/pipelines/deploy_ami.py
    input_files:
      - *tools-admin
      - *deployment-edge
      - "../gomatic-secure/gocd/vars/tools/deploy_edge_ami.yml"
    enabled: True

  - script: edxpipelines/pipelines/deploy_ami.py
    input_files:
      - *tools-admin
      - *deployment-mckinsey
      - "../gomatic-secure/gocd/vars/tools/deploy_mckinsey_ami.yml"
    enabled: True

  - script: edxpipelines/pipelines/deploy_gomatic_pipelines.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/deploy_gomatic_piplines.yml"
    enabled: True

  ## end of deploy pipeline group

  - script: edxpipelines/pipelines/deploy_marketing_site.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/deploy_drupal.yml"
    enabled: False


  ## START OF EDXAPP WHICH BUILDS PROD/EDGE AMIS in PARALLEL WITH STAGE DEPLOYMENT
  # Starts the build of prod AMIs earlier in pipeline.

  # Pre-release pipeline which includes all materials.
  - script: edxpipelines/pipelines/prerelease_materials.py
    input_files:
      - *tools-admin
      - *stage-edx
      - *prod-stage-edxapp
      - "../gomatic-secure/gocd/vars/tools/edxapp-prerelease-materials.yml"
    enabled: True

  # Now the three pipelines which fan-out from pre-release:
  # - Stage B/M/D
  # - prod-edx Build
  # - prod-edge Build

  # Stage edxapp B/M/D
  - script: edxpipelines/pipelines/cd_edxapp_latest.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-edxapp-latest.yml"
      - *stage-edx
      - *prod-stage-edxapp
      - *play-edxapp
      - *deployment-edx
      - *prerelease_upstream
    enabled: True

  # Prod edx of edxapp - but only building!
  - script: edxpipelines/pipelines/cd_edxapp_latest.py
    input_files:
      - *tools-admin
      - *prod-edx-edxapp-latest
      - *prod-edx
      - *prod-stage-edxapp
      - *play-edxapp
      - *deployment-edx
      - *prerelease_upstream
    bmd_steps: "b"
    enabled: True

    # Prod EDGE of edxapp - but only building!
  - script: edxpipelines/pipelines/cd_edxapp_latest.py
    input_files:
      - *tools-admin
      - *prod-edge-edxapp-latest
      - *prod-edge
      - *prod-stage-edxapp
      - *play-edxapp
      - *deployment-edge
      - *prerelease_upstream
    bmd_steps: "b"
    enabled: True

  # The three pipelines above fan-in to the following single pipeline, which allows manual
  # gating of when/if a release candidate is pushed to production.

  # Manual verification pipeline
  - script: edxpipelines/pipelines/manual_verification.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-play/edxapp-manual-verification-latest.yml"
      - *prod-stage-edxapp
    enabled: True

  # When manually triggered in the pipeline above, the following two pipelines migrate/deploy
  # to the production EDX and EDGE environments.

  # Prod edx of edxapp - only migration and deployment.
  - script: edxpipelines/pipelines/cd_edxapp_latest.py
    input_files:
      - *tools-admin
      - *prod-edx-edxapp-latest
      - *prod-edx
      - *prod-stage-edxapp
      - *play-edxapp
      - *deployment-edx
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edx-edxapp-gated-upstream.yml"
    bmd_steps: "md"
    enabled: True

  # Prod EDGE of edxapp - only migration and deployment.
  - script: edxpipelines/pipelines/cd_edxapp_latest.py
    input_files:
      - *tools-admin
      - *prod-edge-edxapp-latest
      - *prod-edge
      - *prod-stage-edxapp
      - *play-edxapp
      - *deployment-edge
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edge-edxapp-gated-upstream.yml"
    bmd_steps: "md"
    enabled: True

  # Then rollback pipelines for both EDX and EDGE are created below.

  # Rollback pipeline for prod edx
  - script: edxpipelines/pipelines/rollback_asgs.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edx-edxapp-rollback-asgs-latest.yml"
      - *prod-stage-edxapp
      - *deployment-edx
    enabled: True

  # Rollback pipeline for prod edge
  - script: edxpipelines/pipelines/rollback_asgs.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edge-edxapp-rollback-asgs-latest.yml"
      - *prod-stage-edxapp
      - *deployment-edge
    enabled: True

  ## END OF EDXAPP WHICH BUILDS PROD/EDGE AMIS in PARALLEL WITH STAGE DEPLOYMENT

  ## Start Edxapp
  # loadtest of edxapp
  - script: edxpipelines/pipelines/cd_edxapp.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/loadtest-edx-edxapp.yml"
      - *loadtest-edx
      - "../gomatic-secure/gocd/vars/tools/environment-play/loadtest-edxapp.yml"
      - *play-edxapp
      - *deployment-edx
    enabled: True

    ## End Edxapp

    ## Start Edxapp-private
    # loadtest of edxapp
  - script: edxpipelines/pipelines/cd_edxapp.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/loadtest-edx-edxapp-private.yml"
      - *loadtest-edx
      - *prod-stage-edxapp-private
      - *play-edxapp
      - *deployment-edx
    enabled: True

  # Stage edxapp
  - script: edxpipelines/pipelines/cd_edxapp.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-edxapp-private.yml"
      - *stage-edx
      - *prod-stage-edxapp-private
      - *play-edxapp
      - *deployment-edx
    enabled: True

  # Manual verification pipeline
  - script: edxpipelines/pipelines/manual_verification.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edx-edxapp-private-manual-verification.yml"
      - *prod-stage-edxapp-private
    enabled: True

  # Prod edx of edxapp
  - script: edxpipelines/pipelines/cd_edxapp.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edx-edxapp-private.yml"
      - *prod-edx
      - *prod-stage-edxapp-private
      - *play-edxapp
      - *deployment-edx
    enabled: True

  # Rollback pipeline for prod edx private
  - script: edxpipelines/pipelines/rollback_asgs.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edx-edxapp-private-rollback-asgs.yml"
      - *prod-stage-edxapp-private
      - *deployment-edx
    enabled: True

  # Prod EDGE of edxapp
  - script: edxpipelines/pipelines/cd_edxapp.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edge-edxapp-private.yml"
      - *prod-edge
      - *prod-stage-edxapp-private
      - *play-edxapp
      - *deployment-edge
    enabled: True

  # Rollback pipeline for prod edge private
  - script: edxpipelines/pipelines/rollback_asgs.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-edge-edxapp-rollback-asgs.yml"
      - *prod-stage-edxapp-private
      - *deployment-edge
    enabled: True

  # Prod McKinsey of edxapp
  - script: edxpipelines/pipelines/cd_edxapp.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/prod-mckinsey-edxapp-private.yml"
      - *prod-mckinsey
      - *prod-stage-edxapp-private
      - *play-edxapp
      - *deployment-mckinsey
    enabled: True

  ## END Edxapp-private

  ## start of api-manager pipeline group

  # build
  - script: edxpipelines/pipelines/api_build.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/build-edx-api.yml"
    enabled: True

  # stage deploy
  - script: edxpipelines/pipelines/api_deploy.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/stage-edx-api.yml"
    enabled: True

  # prod deploy
  - script: edxpipelines/pipelines/api_deploy.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/prod-edx-api.yml"
    enabled: True

    ## end of api-manager pipeline group

  # Analytics
  # Stage insights
  - script: edxpipelines/pipelines/cd_insights.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-insights.yml"
      - *stage-edx
      - "../gomatic-secure/gocd/vars/tools/plays/insights.yml"
      - *deployment-edx
    enabled: True

  # Stage Analytics API
  - script: edxpipelines/pipelines/cd_analyticsapi.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-analyticsapi.yml"
      - *stage-edx
      - "../gomatic-secure/gocd/vars/tools/plays/analyticsapi.yml"
      - *deployment-edx
    enabled: True

  # E-Commerce Apps
  # E-Commerce Service (Otto)
  - script: edxpipelines/pipelines/cd_ecommerce.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-ecommerce.yml"
      - *stage-edx
      - *play-ecommerce
      - *deployment-edx
    enabled: True

  - script: edxpipelines/pipelines/cd_ecommerce.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/loadtest-edx-ecommerce.yml"
      - *loadtest-edx
      - *play-ecommerce
      - *deployment-edx
    enabled: True

  # Credentials Service
  - script: edxpipelines/pipelines/cd_credentials.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-credentials.yml"
      - *stage-edx
      - *play-credentials
      - *deployment-edx
    enabled: True

  - script: edxpipelines/pipelines/cd_credentials.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/loadtest-edx-credentials.yml"
      - *loadtest-edx
      - *play-credentials
      - *deployment-edx
    enabled: True

  # Programs Service
  - script: edxpipelines/pipelines/cd_programs.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-programs.yml"
      - *stage-edx
      - *play-programs
      - *deployment-edx
    enabled: True

  - script: edxpipelines/pipelines/cd_programs.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/loadtest-edx-programs.yml"
      - *loadtest-edx
      - *play-programs
      - *deployment-edx
    enabled: True

  # Catalog/Discovery Service
  - script: edxpipelines/pipelines/cd_discovery.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-discovery.yml"
      - *stage-edx
      - *play-discovery
      - *deployment-edx
    enabled: True

  - script: edxpipelines/pipelines/cd_discovery.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/loadtest-edx-discovery.yml"
      - *loadtest-edx
      - *play-discovery
      - *deployment-edx
    enabled: True

  # E-Commerce Worker
  - script: edxpipelines/pipelines/cd_ecomworker.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/stage-edx-ecomworker.yml"
      - *stage-edx
      - *play-ecomworker
      - *deployment-edx
    enabled: True

  - script: edxpipelines/pipelines/cd_ecomworker.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/loadtest-edx-ecomworker.yml"
      - *loadtest-edx
      - *play-ecomworker
      - *deployment-edx
    enabled: True

sandbox:
  - script: edxpipelines/pipelines/deploy_marketing_site.py
    input_files:
      - "../gomatic-secure/gocd/vars/sandbox/admin.yml"
      - "../gomatic-secure/gocd/vars/sandbox/deploy_drupal.yml"
    enabled: False

  # CD to loadtest of edxapp
  - script: edxpipelines/pipelines/cd_edxapp.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/sandbox/loadtest-edxapp.yml"
    enabled: False
