tools:
  - script: edxpipelines/pipelines/cd_programs_multistage.py
    input_files:
      - &tools-admin "../gomatic-secure/gocd/vars/tools/admin.yml"
      - "../gomatic-secure/gocd/vars/tools/loadtest-multistage-programs.yml"
    enabled: True

  - script: edxpipelines/pipelines/asg_cleanup.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/asg-cleanup-edge.yml"
    enabled: True

  - script: edxpipelines/pipelines/asg_cleanup.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/asg-cleanup-edx.yml"
    enabled: True

  - script: edxpipelines/pipelines/asg_cleanup.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/asg-cleanup-mckinsey.yml"
    enabled: True

  - script: edxpipelines/pipelines/build_edxapp_ami.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/build-edxapp-ami.yml"
    enabled: False

  - script: edxpipelines/pipelines/deploy_ami.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/deploy_edge_ami.yml"
    enabled: False

  - script: edxpipelines/pipelines/deploy_gomatic_pipelines.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/deploy_gomatic_piplines.yml"
    enabled: True

  - script: edxpipelines/pipelines/deploy_marketing_site.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/deploy_drupal.yml"
    enabled: False

  # CD to loadtest of edxapp
  - script: edxpipelines/pipelines/cd_edxapp.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/tools/environment-deployment-play/loadtest-edx-edxapp.yml"
      - "../gomatic-secure/gocd/vars/tools/environments-deployments/loadtest-edx.yml"
      - "../gomatic-secure/gocd/vars/tools/plays/edxapp.yml"
      - "../gomatic-secure/gocd/vars/tools/deployments/edx.yml"
    enabled: True

sandbox:
  - script: edxpipelines/pipelines/cd_programs_multistage.py
    input_files:
      - &sandbox-admin "../gomatic-secure/gocd/vars/sandbox/admin.yml"
      - "../gomatic-secure/gocd/vars/sandbox/loadtest-multistage-programs.yml"
    enabled: True

  - script: edxpipelines/pipelines/deploy_marketing_site.py
    input_files:
      - *sandbox-admin
      - "../gomatic-secure/gocd/vars/sandbox/deploy_drupal.yml"
    enabled: False

  # CD to loadtest of edxapp
  - script: edxpipelines/pipelines/cd_edxapp.py
    input_files:
      - *tools-admin
      - "../gomatic-secure/gocd/vars/sandbox/loadtest-edxapp.yml"
    enabled: False
