pipeline_group: "edxapp_prod_deploys"
pipeline_name: "manual_verification_edxapp_prod_early_ami_build"
upstream_pipelines:
  - pipeline_name: "STAGE_edxapp_B-M-D"
    stage_name: "cleanup_ami_Instance"
    material_name: "stage_edxapp_upstream_material"
  - pipeline_name: "PROD_edx_edxapp_B"
    stage_name: "build_ami"
    material_name: "PROD_edx_edxapp_ami_build"
  - pipeline_name: "PROD_edge_edxapp_B"
    stage_name: "build_ami"
    material_name: "PROD_edge_edxapp_ami_build"
jenkins_verifications:
  - pipeline_job_name: 'edx-e2e-test'
    url: "https://test-jenkins.testeng.edx.org"
    job_name: "jz-test-project"
    param: "EXIT_CODE 0"
  - pipeline_job_name: 'microsites-staging-tests'
    url: "https://test-jenkins.testeng.edx.org"
    job_name: "jz-test-project"
    param: "EXIT_CODE 0"
